window.esdocSearchIndex = [
  [
    "robot/javascript/classes/grid.js~grid",
    "class/javascript/classes/grid.js~Grid.html",
    "<span>Grid</span> <span class=\"search-result-import-path\">robot/javascript/classes/grid.js</span>",
    "class"
  ],
  [
    "robot/javascript/classes/reporter.js~reporter",
    "class/javascript/classes/reporter.js~Reporter.html",
    "<span>Reporter</span> <span class=\"search-result-import-path\">robot/javascript/classes/reporter.js</span>",
    "class"
  ],
  [
    "robot/javascript/classes/robot.js~robot",
    "class/javascript/classes/robot.js~Robot.html",
    "<span>Robot</span> <span class=\"search-result-import-path\">robot/javascript/classes/robot.js</span>",
    "class"
  ],
  [
    "robot/javascript/classes/sound-board.js~soundboard",
    "class/javascript/classes/sound-board.js~SoundBoard.html",
    "<span>SoundBoard</span> <span class=\"search-result-import-path\">robot/javascript/classes/sound-board.js</span>",
    "class"
  ],
  [
    "robot/javascript/classes/speech-parser.js~speechparser",
    "class/javascript/classes/speech-parser.js~SpeechParser.html",
    "<span>SpeechParser</span> <span class=\"search-result-import-path\">robot/javascript/classes/speech-parser.js</span>",
    "class"
  ],
  [
    "robot/javascript/classes/text-parser.js~textparser",
    "class/javascript/classes/text-parser.js~TextParser.html",
    "<span>TextParser</span> <span class=\"search-result-import-path\">robot/javascript/classes/text-parser.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "javascript/classes/grid.js",
    "file/javascript/classes/grid.js.html",
    "javascript/classes/grid.js",
    "file"
  ],
  [
    "javascript/classes/grid.js~grid#canvas",
    "class/javascript/classes/grid.js~Grid.html#instance-member-canvas",
    "javascript/classes/grid.js~Grid#canvas",
    "member"
  ],
  [
    "javascript/classes/grid.js~grid#checktouch",
    "class/javascript/classes/grid.js~Grid.html#instance-method-checkTouch",
    "javascript/classes/grid.js~Grid#checkTouch",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#clamp",
    "class/javascript/classes/grid.js~Grid.html#instance-method-clamp",
    "javascript/classes/grid.js~Grid#clamp",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#constructor",
    "class/javascript/classes/grid.js~Grid.html#instance-constructor-constructor",
    "javascript/classes/grid.js~Grid#constructor",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#createcanvas",
    "class/javascript/classes/grid.js~Grid.html#instance-method-createCanvas",
    "javascript/classes/grid.js~Grid#createCanvas",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#ctx",
    "class/javascript/classes/grid.js~Grid.html#instance-member-ctx",
    "javascript/classes/grid.js~Grid#ctx",
    "member"
  ],
  [
    "javascript/classes/grid.js~grid#draw",
    "class/javascript/classes/grid.js~Grid.html#instance-method-draw",
    "javascript/classes/grid.js~Grid#draw",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#el",
    "class/javascript/classes/grid.js~Grid.html#instance-member-el",
    "javascript/classes/grid.js~Grid#el",
    "member"
  ],
  [
    "javascript/classes/grid.js~grid#layout",
    "class/javascript/classes/grid.js~Grid.html#instance-method-layout",
    "javascript/classes/grid.js~Grid#layout",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#listen",
    "class/javascript/classes/grid.js~Grid.html#instance-method-listen",
    "javascript/classes/grid.js~Grid#listen",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#offsetx",
    "class/javascript/classes/grid.js~Grid.html#instance-member-offsetX",
    "javascript/classes/grid.js~Grid#offsetX",
    "member"
  ],
  [
    "javascript/classes/grid.js~grid#offsety",
    "class/javascript/classes/grid.js~Grid.html#instance-member-offsetY",
    "javascript/classes/grid.js~Grid#offsetY",
    "member"
  ],
  [
    "javascript/classes/grid.js~grid#rotate",
    "class/javascript/classes/grid.js~Grid.html#instance-method-rotate",
    "javascript/classes/grid.js~Grid#rotate",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#startrotate",
    "class/javascript/classes/grid.js~Grid.html#instance-method-startRotate",
    "javascript/classes/grid.js~Grid#startRotate",
    "method"
  ],
  [
    "javascript/classes/grid.js~grid#stoprotate",
    "class/javascript/classes/grid.js~Grid.html#instance-method-stopRotate",
    "javascript/classes/grid.js~Grid#stopRotate",
    "method"
  ],
  [
    "javascript/classes/reporter.js",
    "file/javascript/classes/reporter.js.html",
    "javascript/classes/reporter.js",
    "file"
  ],
  [
    "javascript/classes/reporter.js~reporter#constructor",
    "class/javascript/classes/reporter.js~Reporter.html#instance-constructor-constructor",
    "javascript/classes/reporter.js~Reporter#constructor",
    "method"
  ],
  [
    "javascript/classes/reporter.js~reporter#container",
    "class/javascript/classes/reporter.js~Reporter.html#instance-member-container",
    "javascript/classes/reporter.js~Reporter#container",
    "member"
  ],
  [
    "javascript/classes/reporter.js~reporter#listitem",
    "class/javascript/classes/reporter.js~Reporter.html#instance-method-listItem",
    "javascript/classes/reporter.js~Reporter#listItem",
    "method"
  ],
  [
    "javascript/classes/reporter.js~reporter#listen",
    "class/javascript/classes/reporter.js~Reporter.html#instance-method-listen",
    "javascript/classes/reporter.js~Reporter#listen",
    "method"
  ],
  [
    "javascript/classes/reporter.js~reporter#report",
    "class/javascript/classes/reporter.js~Reporter.html#instance-method-report",
    "javascript/classes/reporter.js~Reporter#report",
    "method"
  ],
  [
    "javascript/classes/robot.js",
    "file/javascript/classes/robot.js.html",
    "javascript/classes/robot.js",
    "file"
  ],
  [
    "javascript/classes/robot.js~robot#animate",
    "class/javascript/classes/robot.js~Robot.html#instance-method-animate",
    "javascript/classes/robot.js~Robot#animate",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#broadcast",
    "class/javascript/classes/robot.js~Robot.html#instance-method-broadcast",
    "javascript/classes/robot.js~Robot#broadcast",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#clamprotation",
    "class/javascript/classes/robot.js~Robot.html#instance-method-clampRotation",
    "javascript/classes/robot.js~Robot#clampRotation",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#connectto",
    "class/javascript/classes/robot.js~Robot.html#instance-method-connectTo",
    "javascript/classes/robot.js~Robot#connectTo",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#constructor",
    "class/javascript/classes/robot.js~Robot.html#instance-constructor-constructor",
    "javascript/classes/robot.js~Robot#constructor",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#grid",
    "class/javascript/classes/robot.js~Robot.html#instance-member-grid",
    "javascript/classes/robot.js~Robot#grid",
    "member"
  ],
  [
    "javascript/classes/robot.js~robot#handleclick",
    "class/javascript/classes/robot.js~Robot.html#instance-method-handleClick",
    "javascript/classes/robot.js~Robot#handleClick",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#handlekeypress",
    "class/javascript/classes/robot.js~Robot.html#instance-method-handleKeypress",
    "javascript/classes/robot.js~Robot#handleKeypress",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#left",
    "class/javascript/classes/robot.js~Robot.html#instance-method-left",
    "javascript/classes/robot.js~Robot#left",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#listen",
    "class/javascript/classes/robot.js~Robot.html#instance-method-listen",
    "javascript/classes/robot.js~Robot#listen",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#move",
    "class/javascript/classes/robot.js~Robot.html#instance-method-move",
    "javascript/classes/robot.js~Robot#move",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#moving",
    "class/javascript/classes/robot.js~Robot.html#instance-member-moving",
    "javascript/classes/robot.js~Robot#moving",
    "member"
  ],
  [
    "javascript/classes/robot.js~robot#place",
    "class/javascript/classes/robot.js~Robot.html#instance-method-place",
    "javascript/classes/robot.js~Robot#place",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#placed",
    "class/javascript/classes/robot.js~Robot.html#instance-member-placed",
    "javascript/classes/robot.js~Robot#placed",
    "member"
  ],
  [
    "javascript/classes/robot.js~robot#queue",
    "class/javascript/classes/robot.js~Robot.html#instance-member-queue",
    "javascript/classes/robot.js~Robot#queue",
    "member"
  ],
  [
    "javascript/classes/robot.js~robot#registercommands",
    "class/javascript/classes/robot.js~Robot.html#instance-method-registerCommands",
    "javascript/classes/robot.js~Robot#registerCommands",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#render",
    "class/javascript/classes/robot.js~Robot.html#instance-method-render",
    "javascript/classes/robot.js~Robot#render",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#report",
    "class/javascript/classes/robot.js~Robot.html#instance-method-report",
    "javascript/classes/robot.js~Robot#report",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#right",
    "class/javascript/classes/robot.js~Robot.html#instance-method-right",
    "javascript/classes/robot.js~Robot#right",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#robot",
    "class/javascript/classes/robot.js~Robot.html#instance-member-robot",
    "javascript/classes/robot.js~Robot#robot",
    "member"
  ],
  [
    "javascript/classes/robot.js~robot#rotate",
    "class/javascript/classes/robot.js~Robot.html#instance-method-rotate",
    "javascript/classes/robot.js~Robot#rotate",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#validatef",
    "class/javascript/classes/robot.js~Robot.html#instance-method-validateF",
    "javascript/classes/robot.js~Robot#validateF",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#validatex",
    "class/javascript/classes/robot.js~Robot.html#instance-method-validateX",
    "javascript/classes/robot.js~Robot#validateX",
    "method"
  ],
  [
    "javascript/classes/robot.js~robot#validatey",
    "class/javascript/classes/robot.js~Robot.html#instance-method-validateY",
    "javascript/classes/robot.js~Robot#validateY",
    "method"
  ],
  [
    "javascript/classes/sound-board.js",
    "file/javascript/classes/sound-board.js.html",
    "javascript/classes/sound-board.js",
    "file"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#audio",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-member-audio",
    "javascript/classes/sound-board.js~SoundBoard#audio",
    "member"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#constructor",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-constructor-constructor",
    "javascript/classes/sound-board.js~SoundBoard#constructor",
    "method"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#listen",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-method-listen",
    "javascript/classes/sound-board.js~SoundBoard#listen",
    "method"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#play",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-method-play",
    "javascript/classes/sound-board.js~SoundBoard#play",
    "method"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#reset",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-method-reset",
    "javascript/classes/sound-board.js~SoundBoard#reset",
    "method"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#soundon",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-member-soundOn",
    "javascript/classes/sound-board.js~SoundBoard#soundOn",
    "member"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#togglesound",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-method-toggleSound",
    "javascript/classes/sound-board.js~SoundBoard#toggleSound",
    "method"
  ],
  [
    "javascript/classes/sound-board.js~soundboard#toggles",
    "class/javascript/classes/sound-board.js~SoundBoard.html#instance-member-toggles",
    "javascript/classes/sound-board.js~SoundBoard#toggles",
    "member"
  ],
  [
    "javascript/classes/speech-parser.js",
    "file/javascript/classes/speech-parser.js.html",
    "javascript/classes/speech-parser.js",
    "file"
  ],
  [
    "javascript/classes/speech-parser.js~speechparser#commands",
    "class/javascript/classes/speech-parser.js~SpeechParser.html#instance-member-commands",
    "javascript/classes/speech-parser.js~SpeechParser#commands",
    "member"
  ],
  [
    "javascript/classes/speech-parser.js~speechparser#constructor",
    "class/javascript/classes/speech-parser.js~SpeechParser.html#instance-constructor-constructor",
    "javascript/classes/speech-parser.js~SpeechParser#constructor",
    "method"
  ],
  [
    "javascript/classes/speech-parser.js~speechparser#listen",
    "class/javascript/classes/speech-parser.js~SpeechParser.html#instance-method-listen",
    "javascript/classes/speech-parser.js~SpeechParser#listen",
    "method"
  ],
  [
    "javascript/classes/speech-parser.js~speechparser#mumble",
    "class/javascript/classes/speech-parser.js~SpeechParser.html#instance-member-mumble",
    "javascript/classes/speech-parser.js~SpeechParser#mumble",
    "member"
  ],
  [
    "javascript/classes/speech-parser.js~speechparser#robot",
    "class/javascript/classes/speech-parser.js~SpeechParser.html#instance-member-robot",
    "javascript/classes/speech-parser.js~SpeechParser#robot",
    "member"
  ],
  [
    "javascript/classes/text-parser.js",
    "file/javascript/classes/text-parser.js.html",
    "javascript/classes/text-parser.js",
    "file"
  ],
  [
    "javascript/classes/text-parser.js~textparser#adddropstate",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-addDropState",
    "javascript/classes/text-parser.js~TextParser#addDropState",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#canceldigest",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-cancelDigest",
    "javascript/classes/text-parser.js~TextParser#cancelDigest",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#commands",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-member-commands",
    "javascript/classes/text-parser.js~TextParser#commands",
    "member"
  ],
  [
    "javascript/classes/text-parser.js~textparser#constructor",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-constructor-constructor",
    "javascript/classes/text-parser.js~TextParser#constructor",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#digest",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-digest",
    "javascript/classes/text-parser.js~TextParser#digest",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#enqueue",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-enqueue",
    "javascript/classes/text-parser.js~TextParser#enqueue",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#interval",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-member-interval",
    "javascript/classes/text-parser.js~TextParser#interval",
    "member"
  ],
  [
    "javascript/classes/text-parser.js~textparser#listen",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-listen",
    "javascript/classes/text-parser.js~TextParser#listen",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#loadfile",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-loadFile",
    "javascript/classes/text-parser.js~TextParser#loadFile",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#parsing",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-member-parsing",
    "javascript/classes/text-parser.js~TextParser#parsing",
    "member"
  ],
  [
    "javascript/classes/text-parser.js~textparser#queue",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-member-queue",
    "javascript/classes/text-parser.js~TextParser#queue",
    "member"
  ],
  [
    "javascript/classes/text-parser.js~textparser#readln",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-readLn",
    "javascript/classes/text-parser.js~TextParser#readLn",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#removedropstate",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-removeDropState",
    "javascript/classes/text-parser.js~TextParser#removeDropState",
    "method"
  ],
  [
    "javascript/classes/text-parser.js~textparser#robot",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-member-robot",
    "javascript/classes/text-parser.js~TextParser#robot",
    "member"
  ],
  [
    "javascript/classes/text-parser.js~textparser#tick",
    "class/javascript/classes/text-parser.js~TextParser.html#instance-method-tick",
    "javascript/classes/text-parser.js~TextParser#tick",
    "method"
  ],
  [
    "javascript/main.js",
    "file/javascript/main.js.html",
    "javascript/main.js",
    "file"
  ]
]